import streamlit as st
import streamlit.components.v1 as components
from pptx import Presentation
import anthropic
import json
import pandas as pd

# ─────────────────────────────────────────────
# Page config
# ─────────────────────────────────────────────
st.set_page_config(
    page_title="AI 기획 리뷰 툴",
    page_icon="🤖",
    layout="wide",
)

# ─────────────────────────────────────────────
# Leave warning
# ─────────────────────────────────────────────
def inject_leave_warning(enabled: bool):
    script = f"""
    <script>
    const warningEnabled = {str(enabled).lower()};
    window.onbeforeunload = null;

    if (warningEnabled) {{
        window.onbeforeunload = function (e) {{
            e.preventDefault();
            e.returnValue = '';
            return '';
        }};
    }}
    </script>
    """
    components.html(script, height=0)

# ─────────────────────────────────────────────
# HTML report helper
# ─────────────────────────────────────────────
def build_html_report(ux_issues, policy_gaps, edge_cases, test_cases):
    ux_df = pd.DataFrame([
        {
            "Title": item.get("title", ""),
            "Description": item.get("description", ""),
            "Impact": item.get("impact", ""),
        }
        for item in ux_issues
    ])

    policy_df = pd.DataFrame([
        {
            "Title": item.get("title", ""),
            "Description": item.get("description", ""),
            "Recommendation": item.get("recommendation", ""),
        }
        for item in policy_gaps
    ])

    edge_df = pd.DataFrame([
        {
            "Title": item.get("title", ""),
            "Scenario": item.get("scenario", ""),
            "Expected Behavior": item.get("expected_behavior", ""),
        }
        for item in edge_cases
    ])

    test_case_df = pd.DataFrame([
        {
            "TC #": t.get("id", ""),
            "Test Case": t.get("test_case", ""),
            "Description": t.get("description", ""),
            "Expected Result": t.get("expected_result", ""),
            "Priority": t.get("priority", ""),
        }
        for t in test_cases
    ])

    def table_or_empty(df, empty_text="결과 없음"):
        if df.empty:
            return f"<p>{empty_text}</p>"
        return df.to_html(index=False, escape=False)

    return f"""
    <!DOCTYPE html>
    <html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>AI 기획 리뷰 결과</title>
        <style>
            body {{
                font-family: Arial, sans-serif;
                margin: 32px;
                color: #1e293b;
                line-height: 1.6;
            }}
            h1 {{
                margin-bottom: 8px;
            }}
            h2 {{
                margin-top: 32px;
                border-bottom: 2px solid #e2e8f0;
                padding-bottom: 6px;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin-top: 12px;
                margin-bottom: 28px;
                table-layout: fixed;
                word-wrap: break-word;
            }}
            th, td {{
                border: 1px solid #cbd5e1;
                padding: 10px;
                text-align: left;
                vertical-align: top;
                font-size: 14px;
            }}
            th {{
                background: #f1f5f9;
            }}
            .meta {{
                color: #64748b;
                margin-bottom: 24px;
            }}
        </style>
    </head>
    <body>
        <h1>AI 기획 리뷰 결과</h1>
        <div class="meta">
            <div>Generated by AI Planning Review Tool</div>
        </div>

        <h2>1. UX Issues</h2>
        {table_or_empty(ux_df)}

        <h2>2. Policy Gaps</h2>
        {table_or_empty(policy_df)}

        <h2>3. Edge Cases</h2>
        {table_or_empty(edge_df)}

        <h2>4. QA Test Cases</h2>
        {table_or_empty(test_case_df)}
    </body>
    </html>
    """

# ─────────────────────────────────────────────
# Custom CSS
# ─────────────────────────────────────────────
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR:wght@400;500;600&family=IBM+Plex+Mono:wght@400;600&display=swap');

    html, body, [class*="css"] {
        font-family: 'IBM Plex Sans KR', sans-serif;
    }

    .main-header {
        background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
        color: #f8fafc;
        padding: 2rem 2.5rem;
        border-radius: 12px;
        margin-bottom: 2rem;
        border-left: 4px solid #6366f1;
    }
    .main-header h1 { margin: 0; font-size: 1.8rem; font-weight: 600; }
    .main-header p  { margin: 0.4rem 0 0; color: #94a3b8; font-size: 0.9rem; }

    .section-title {
        font-size: 1.05rem;
        font-weight: 600;
        color: #1e293b;
        border-bottom: 2px solid #e2e8f0;
        padding-bottom: 0.5rem;
        margin-bottom: 1rem;
        margin-top: 1.5rem;
    }

    .slide-card {
        background: #f8fafc;
        border: 1px solid #e2e8f0;
        border-radius: 8px;
        padding: 1rem 1.2rem;
        margin-bottom: 0.8rem;
        font-size: 0.85rem;
        line-height: 1.7;
    }

    .stat-box {
        background: #f1f5f9;
        border-radius: 8px;
        padding: 1rem;
        text-align: center;
    }
    .stat-box .num { font-size: 2rem; font-weight: 700; color: #6366f1; }
    .stat-box .lbl { font-size: 0.8rem; color: #64748b; margin-top: 2px; }
</style>
""", unsafe_allow_html=True)

# ─────────────────────────────────────────────
# Sidebar – API Key 입력
# ─────────────────────────────────────────────
with st.sidebar:
    st.markdown("### 🔑 API 설정")
    api_key = st.text_input(
        "Anthropic API Key",
        type="password",
        placeholder="sk-ant-api03-...",
        help="https://console.anthropic.com 에서 발급받은 API 키를 입력하세요.",
    )
    if api_key:
        st.success("API 키 입력 완료", icon="✅")
    else:
        st.warning("API 키를 입력해야 리뷰 결과 생성이 가능합니다.", icon="⚠️")

    st.markdown("---")
    st.markdown("**API 키 발급 방법**")
    st.markdown("1. [console.anthropic.com](https://console.anthropic.com) 접속")
    st.markdown("2. **API Keys** 메뉴 → **Create Key**")
    st.markdown("3. 발급된 키를 위 입력란에 붙여넣기")

# ─────────────────────────────────────────────
# Header
# ─────────────────────────────────────────────
st.markdown("""
<div class="main-header">
    <h1>🤖 AI 기획 리뷰 툴</h1>
    <p>PPT 기획안을 업로드하면 AI가 UX Issues, Policy Gaps, Edge Cases, QA Test Cases를 자동으로 생성합니다.</p>
</div>
""", unsafe_allow_html=True)

# ─────────────────────────────────────────────
# File upload
# ─────────────────────────────────────────────
uploaded_file = st.file_uploader("📎 PPT 기획안 업로드 (.pptx)", type=["pptx"])

# 파일 업로드된 상태에서만 새로고침/이탈 경고 활성화
inject_leave_warning(uploaded_file is not None)

if uploaded_file:
    # ── PPT 텍스트 추출 ───────────────────────
    prs = Presentation(uploaded_file)
    all_text = ""
    slide_texts = []

    for i, slide in enumerate(prs.slides):
        text = ""
        for shape in slide.shapes:
            if shape.shape_type == 19:  # TABLE
                table = shape.table
                for row in table.rows:
                    row_texts = []
                    for cell in row.cells:
                        cell_text = cell.text.strip()
                        if cell_text:
                            row_texts.append(cell_text)
                    if row_texts:
                        text += " | ".join(row_texts) + "\n"
            elif hasattr(shape, "text") and shape.text.strip():
                text += shape.text.strip() + "\n"

        slide_texts.append((i + 1, text))
        all_text += text + "\n"

    # ── 슬라이드 미리보기 ─────────────────────
    with st.expander("📄 추출된 PPT 내용 보기", expanded=False):
        for slide_num, text in slide_texts:
            if text.strip():
                st.markdown(f"**Slide {slide_num}**")
                st.markdown(
                    '<div class="slide-card">' + text.replace("\n", "<br>") + '</div>',
                    unsafe_allow_html=True,
                )

    st.divider()

    # ── Claude 채팅용 프롬프트 ────────────────
    st.markdown('<div class="section-title">🧠 Claude 채팅에 붙여넣을 프롬프트</div>', unsafe_allow_html=True)
    st.caption("API 키 없이도 claude.ai 채팅창에 아래 프롬프트를 복사해서 바로 사용할 수 있습니다.")

    prompt = (
        "다음은 서비스 기획안이다.\n\n"
        "이 내용을 분석해서 다음을 작성하라.\n\n"
        "1. UX Issues\n"
        "2. Policy Gaps\n"
        "3. Edge Cases\n"
        "4. QA Test Cases\n\n"
        "기획안 내용:\n"
        + all_text
    )

    col_prompt, col_btn = st.columns([5, 1])
    with col_prompt:
        st.text_area(
            "프롬프트 (복사 후 claude.ai 채팅창에 붙여넣기)",
            value=prompt,
            height=220,
            label_visibility="collapsed",
        )
    with col_btn:
        st.link_button(
            "💬 claude.ai\n열기",
            url="https://claude.ai",
            use_container_width=True,
        )

    st.divider()

    # ── AI 리뷰 생성 버튼 ─────────────────────
    st.markdown('<div class="section-title">🧪 AI 리뷰 결과 생성 (API 키 필요)</div>', unsafe_allow_html=True)

    if st.button("✨ 리뷰 결과 생성하기", type="primary", use_container_width=True):
        if not api_key:
            st.error("왼쪽 사이드바에 Anthropic API 키를 먼저 입력해주세요.")
            st.stop()

        with st.spinner("Claude가 기획안을 분석 중입니다..."):
            client = anthropic.Anthropic(api_key=api_key)

            system_prompt = (
                "당신은 시니어 QA 엔지니어이자 서비스 기획 리뷰어입니다.\n"
                "서비스 기획안을 분석하여 아래 4개 항목을 모두 도출하세요.\n\n"
                "1. UX Issues\n"
                "2. Policy Gaps\n"
                "3. Edge Cases\n"
                "4. QA Test Cases\n\n"
                "반드시 아래 JSON 형식으로만 응답하세요. 다른 텍스트는 포함하지 마세요.\n\n"
                '{\n'
                '  "ux_issues": [\n'
                '    {\n'
                '      "title": "문제 제목",\n'
                '      "description": "문제 설명",\n'
                '      "impact": "유저/비즈니스 영향"\n'
                '    }\n'
                '  ],\n'
                '  "policy_gaps": [\n'
                '    {\n'
                '      "title": "정책 누락 제목",\n'
                '      "description": "누락/모호한 정책 설명",\n'
                '      "recommendation": "권장 정책 또는 보완안"\n'
                '    }\n'
                '  ],\n'
                '  "edge_cases": [\n'
                '    {\n'
                '      "title": "엣지 케이스 제목",\n'
                '      "scenario": "상황 설명",\n'
                '      "expected_behavior": "시스템 기대 동작"\n'
                '    }\n'
                '  ],\n'
                '  "test_cases": [\n'
                '    {\n'
                '      "id": "TC-001",\n'
                '      "test_case": "테스트 케이스 이름",\n'
                '      "description": "상세 테스트 시나리오 설명",\n'
                '      "expected_result": "기대 결과",\n'
                '      "priority": "High"\n'
                '    }\n'
                '  ]\n'
                '}\n\n'
                "priority는 반드시 High / Medium / Low 중 하나만 사용하세요.\n"
                "ux_issues는 최소 5개 이상, policy_gaps는 최소 5개 이상, edge_cases는 최소 8개 이상, test_cases는 최소 15개 이상 생성하세요.\n"
                "각 항목은 구체적으로 작성하세요."
            )

            user_prompt = (
                "다음 서비스 기획안을 분석하여 아래 4개 항목을 모두 JSON으로 생성하세요.\n\n"
                "1. UX Issues\n"
                "2. Policy Gaps\n"
                "3. Edge Cases\n"
                "4. QA Test Cases\n\n"
                "기획안 내용:\n"
                + all_text[:12000]
            )

            response = client.messages.create(
                model="claude-sonnet-4-20250514",
                max_tokens=7000,
                system=system_prompt,
                messages=[{"role": "user", "content": user_prompt}],
            )

            raw = response.content[0].text.strip()

            try:
                if "```" in raw:
                    parts = raw.split("```")
                    if len(parts) > 1:
                        raw = parts[1]
                    if raw.startswith("json"):
                        raw = raw[4:]

                data = json.loads(raw.strip())

                ux_issues = data.get("ux_issues", [])
                policy_gaps = data.get("policy_gaps", [])
                edge_cases = data.get("edge_cases", [])
                test_cases = data.get("test_cases", [])

            except Exception:
                st.error("JSON 파싱 오류가 발생했습니다. 다시 시도해주세요.")
                st.code(raw)
                st.stop()

        # ── 요약 통계 ─────────────────────────
        c1, c2, c3, c4 = st.columns(4)
        with c1:
            st.markdown(
                f'<div class="stat-box"><div class="num">{len(ux_issues)}</div><div class="lbl">UX Issues</div></div>',
                unsafe_allow_html=True,
            )
        with c2:
            st.markdown(
                f'<div class="stat-box"><div class="num">{len(policy_gaps)}</div><div class="lbl">Policy Gaps</div></div>',
                unsafe_allow_html=True,
            )
        with c3:
            st.markdown(
                f'<div class="stat-box"><div class="num">{len(edge_cases)}</div><div class="lbl">Edge Cases</div></div>',
                unsafe_allow_html=True,
            )
        with c4:
            st.markdown(
                f'<div class="stat-box"><div class="num">{len(test_cases)}</div><div class="lbl">QA Test Cases</div></div>',
                unsafe_allow_html=True,
            )

        # ── 1. UX Issues ───────────────────────
        st.markdown('<div class="section-title">1. UX Issues</div>', unsafe_allow_html=True)

        if ux_issues:
            ux_df = pd.DataFrame([
                {
                    "Title": item.get("title", ""),
                    "Description": item.get("description", ""),
                    "Impact": item.get("impact", ""),
                }
                for item in ux_issues
            ])
            st.dataframe(
                ux_df,
                use_container_width=True,
                hide_index=True,
                height=min(80 + len(ux_df) * 55, 500),
            )
        else:
            st.info("UX Issues 결과가 없습니다.")

        # ── 2. Policy Gaps ─────────────────────
        st.markdown('<div class="section-title">2. Policy Gaps</div>', unsafe_allow_html=True)

        if policy_gaps:
            policy_df = pd.DataFrame([
                {
                    "Title": item.get("title", ""),
                    "Description": item.get("description", ""),
                    "Recommendation": item.get("recommendation", ""),
                }
                for item in policy_gaps
            ])
            st.dataframe(
                policy_df,
                use_container_width=True,
                hide_index=True,
                height=min(80 + len(policy_df) * 55, 500),
            )
        else:
            st.info("Policy Gaps 결과가 없습니다.")

        # ── 3. Edge Cases ──────────────────────
        st.markdown('<div class="section-title">3. Edge Cases</div>', unsafe_allow_html=True)

        if edge_cases:
            edge_df = pd.DataFrame([
                {
                    "Title": item.get("title", ""),
                    "Scenario": item.get("scenario", ""),
                    "Expected Behavior": item.get("expected_behavior", ""),
                }
                for item in edge_cases
            ])
            st.dataframe(
                edge_df,
                use_container_width=True,
                hide_index=True,
                height=min(80 + len(edge_df) * 55, 500),
            )
        else:
            st.info("Edge Cases 결과가 없습니다.")

        # ── 4. QA Test Cases ───────────────────
        st.markdown('<div class="section-title">4. QA Test Cases</div>', unsafe_allow_html=True)

        total = len(test_cases)
        high = sum(1 for t in test_cases if t.get("priority") == "High")
        medium = sum(1 for t in test_cases if t.get("priority") == "Medium")
        low = sum(1 for t in test_cases if t.get("priority") == "Low")

        q1, q2, q3, q4 = st.columns(4)
        with q1:
            st.markdown(
                f'<div class="stat-box"><div class="num">{total}</div><div class="lbl">전체 테스트케이스</div></div>',
                unsafe_allow_html=True,
            )
        with q2:
            st.markdown(
                f'<div class="stat-box"><div class="num" style="color:#ef4444">{high}</div><div class="lbl">🔴 High Priority</div></div>',
                unsafe_allow_html=True,
            )
        with q3:
            st.markdown(
                f'<div class="stat-box"><div class="num" style="color:#f59e0b">{medium}</div><div class="lbl">🟡 Medium Priority</div></div>',
                unsafe_allow_html=True,
            )
        with q4:
            st.markdown(
                f'<div class="stat-box"><div class="num" style="color:#10b981">{low}</div><div class="lbl">🟢 Low Priority</div></div>',
                unsafe_allow_html=True,
            )

        priority_filter = st.multiselect(
            "우선순위 필터",
            options=["High", "Medium", "Low"],
            default=["High", "Medium", "Low"],
        )

        filtered = [t for t in test_cases if t.get("priority") in priority_filter]

        if filtered:
            df = pd.DataFrame([
                {
                    "TC #": t.get("id", ""),
                    "Test Case": t.get("test_case", ""),
                    "Description": t.get("description", ""),
                    "Expected Result": t.get("expected_result", ""),
                    "Priority": t.get("priority", ""),
                }
                for t in filtered
            ])

            st.dataframe(
                df,
                use_container_width=True,
                hide_index=True,
                column_config={
                    "TC #": st.column_config.TextColumn("TC #", width="small"),
                    "Test Case": st.column_config.TextColumn("Test Case", width="medium"),
                    "Description": st.column_config.TextColumn("Description", width="large"),
                    "Expected Result": st.column_config.TextColumn("Expected Result", width="large"),
                    "Priority": st.column_config.SelectboxColumn(
                        "Priority",
                        options=["High", "Medium", "Low"],
                        width="small",
                    ),
                },
                height=min(80 + len(filtered) * 55, 700),
            )

            st.download_button(
                label="⬇️ CSV로 다운로드",
                data=df.to_csv(index=False, encoding="utf-8-sig"),
                file_name="qa_test_cases.csv",
                mime="text/csv",
                use_container_width=True,
            )

            html_report = build_html_report(
                ux_issues=ux_issues,
                policy_gaps=policy_gaps,
                edge_cases=edge_cases,
                test_cases=test_cases,
            )

            st.download_button(
                label="🌐 HTML 리포트 다운로드",
                data=html_report,
                file_name="ai_planning_review.html",
                mime="text/html",
                use_container_width=True,
            )
        else:
            st.info("선택된 우선순위에 해당하는 테스트케이스가 없습니다.")